- original_id: 1
  original_name: Hatchback
  yolo_id: 0
  name: Hatchback
- original_id: 2
  original_name: Sedan
  yolo_id: 1
  name: Sedan
- original_id: 3
  original_name: SUV
  yolo_id: 2
  name: SUV
- original_id: 4
  original_name: MUV
  yolo_id: 3
  name: MUV
- original_id: 5
  original_name: Bus
  yolo_id: 4
  name: Bus
- original_id: 6
  original_name: Truck
  yolo_id: 5
  name: Truck
- original_id: 7
  original_name: Three-wheeler
  yolo_id: 6
  name: Three-wheeler
- original_id: 8
  original_name: Two-wheeler
  yolo_id: 7
  name: Two-wheeler
- original_id: 9
  original_name: LCV
  yolo_id: 8
  name: LCV
- original_id: 10
  original_name: Mini-bus
  yolo_id: 9
  name: Mini-bus
- original_id: 11
  original_name: Tempo-traveller
  yolo_id: 10
  name: Tempo-traveller
- original_id: 12
  original_name: Bicycle
  yolo_id: 11
  name: Bicycle
- original_id: 13
  original_name: Van
  yolo_id: 12
  name: Van
- original_id: 14
  original_name: Others
  yolo_id: 13
  name: Others
