model: models/yolov8s.pt
amp: false
batch: 8
close_mosaic: 5
cos_lr: false
deterministic: true
device: mps
epochs: 30
imgsz: 640
lr0: 0.000556
lrf: 0.01
momentum: 0.9
nbs: 64
optimizer: AdamW
patience: 10
plots: true
pretrained: true
save: true
seed: 42
warmup_bias_lr: 0.0
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 0
auto_augment: randaugment
copy_paste: 0.0
cutmix: 0.0
degrees: 0.0
erasing: 0.4
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
mixup: 0.0
mosaic: 1.0
perspective: 0.0
scale: 0.5
shear: 0.0
translate: 0.1
